#
# Lein tasks
#

##################################################
# Test Task
##################################################
test:
  description: Run all tests.
  folder: tests
  commands: unit2 discover

##################################################
# Style checking Task
##################################################
style:
  description: Check pep8 conventions.
  commands: pep8

##################################################
# Clean Task
##################################################
clean:
  description: Clean garbage.
  commands: rm -rf .tox fablein.egg-info build
